                                            Self-Driving Car Research Project

                                                   Data Preprocessing

In [1]:
from __future__ import print_function
from imutils.object_detection import non_max_suppression
from imutils import paths
import numpy as np
import os
import imutils
import cv2

In [14]:
dirs = os.listdir('Images')
for i in range(0,len(dirs)):
    dirs[i] = os.path.join('Images', dirs[i])
paths = []
for dir in dirs:
    if os.path.isfile(dir):
        paths.append(dir)
        continue
    files = os.listdir(dir)
    for file in files:
        paths.append(os.path.join(dir,file))

In [15]:

# initialize the HOG descriptor/person detector
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

In [ ]:
# loop over the image paths
for imagePath in paths:
    # load the image and resize it to (1) reduce detection time
    # and (2) improve detection accuracy
    print(imagePath)
    image = cv2.imread(imagePath)
    print(image)
    image = imutils.resize(image, width=min(400, image.shape[1]))
    orig = image.copy()
 
    # detect people in the image
    (rects, weights) = hog.detectMultiScale(image, winStride=(4, 4),
        padding=(8, 8), scale=1.05)
 
    # draw the original bounding boxes
    for (x, y, w, h) in rects:
        cv2.rectangle(orig, (x, y), (x + w, y + h), (0, 0, 255), 2)
 
    # apply non-maxima suppression to the bounding boxes using a
    # fairly large overlap threshold to try to maintain overlapping
    # boxes that are still people
    rects = np.array([[x, y, x + w, y + h] for (x, y, w, h) in rects])
    pick = non_max_suppression(rects, probs=None, overlapThresh=0.65)
 
    # draw the final bounding boxes
    for (xA, yA, xB, yB) in pick:
        cv2.rectangle(image, (xA, yA), (xB, yB), (0, 255, 0), 2)
 
    # show some information on the number of bounding boxes
    filename = imagePath[imagePath.rfind("/") + 1:]
    print("[INFO] {}: {} original boxes, {} after suppression".format(
        filename, len(rects), len(pick)))
 
    # show the output images
    cv2.imshow("Before NMS", orig)
    cv2.imshow("After NMS", image)
    # Press any key to go on to the next image
    cv2.waitKey(0)

Images/lidar_car.jpg
[[[ 36  34  40]
  [ 27  25  31]
  [ 17  13  24]
  ...
  [ 47  23  55]
  [ 22   3  28]
  [150 134 157]]

 [[ 12  11  21]
  [  3   2  12]
  [ 11   7  18]
  ...
  [ 41  17  47]
  [ 20   1  26]
  [151 135 158]]

 [[  8   7  23]
  [  0   0  13]
  [  8   6  18]
  ...
  [ 43  20  48]
  [ 20   2  25]
  [150 135 156]]

 ...

 [[ 33  23  23]
  [ 18   8   8]
  [ 22  12  12]
  ...
  [  5   4   6]
  [  1   0   4]
  [147 146 150]]

 [[ 28  20  21]
  [ 13   5   6]
  [ 17   9  10]
  ...
  [  3   2   6]
  [  0   0   3]
  [142 141 145]]

 [[ 41  32  35]
  [ 27  18  21]
  [ 30  21  24]
  ...
  [ 11  10  14]
  [  4   3   7]
  [146 145 149]]]
[INFO] lidar_car.jpg: 0 original boxes, 0 after suppression
